var item = [
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["", ""],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["", ""],
  },
];
var theBigDiv = document.getElementById("theBigDiv");
var body = document.getElementsByTagName("body");
