var item = [
  {
    id: "1",
    itemName: "Notch Neck Puff Sleeve Ditsy Floral Blouse",
    price: 30,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/ORHNf", "https://did.li/630ql"],
  },
  {
    id: "2",
    itemName: "Paperbag Waist Dual Pocket Belted Skinny Pants",
    price: 60,
    description: "",
    category: "pants",
    picture: ["https://did.li/4jlTY", "https://did.li/kvNw5"],
  },
  {
    id: "3",
    itemName: "Solid Slant Pocket Wide Leg Shorts",
    price: 40,
    description: "",
    category: "pants",
    picture: ["https://did.li/BGfaa", "https://did.li/030ql"],
  },
  {
    id: "4",
    itemName: "Cut-out One Shoulder Bikini Swimsuit",
    price: 49,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/fMYYH", "https://did.li/N9SfT"],
  },
  {
    id: "5",
    itemName: "Satin Solid Button Through Drop Shoulder Blouse",
    price: 60,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/J9SfT", "https://did.li/hvNw5"],
  },
  {
    id: "6",
    itemName: "Geo Print Ruffle Hem Shirt Dress",
    price: 80,
    description: "",
    category: "dresses",
    picture: ["https://did.li/5jlTY", "https://did.li/lvNw5"],
  },
  {
    id: "7",
    itemName: "Tropical Bandeau High Waisted Bikini Swimsuit",
    price: 39,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/b40ql", "https://did.li/URHNf"],
  },
  {
    id: "8",
    itemName: "Pleated Belted Shirt Dress",
    price: 69,
    description: "",
    category: "dresses",
    picture: ["https://did.li/seC5q", "https://did.li/Jp5Hw"],
  },
  {
    id: "9",
    itemName: "Notched Landscape Print Dress Without Belt",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["https://did.li/1AwlC", "https://did.li/hMYYH"],
  },
  {
    id: "10",
    itemName: "Cut-out Side Bikini Swimsuit",
    price: 39,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/EGfaa", "https://did.li/VRHNf"],
  },
  {
    id: "11",
    itemName: "High Waist Ripped Jeans",
    price: 79,
    description: "",
    category: "pants",
    picture: ["https://did.li/8jlTY", "https://did.li/Q9SfT"],
  },
  {
    id: "12",
    itemName: "Stonewash Distressed Skinny Jeans",
    price: 50,
    description: "",
    category: "pants",
    picture: ["https://did.li/FGfaa", "https://did.li/WRHNf"],
  },
  {
    id: "13",
    itemName: "High Waisted Ripped Skinny Jeans",
    price: 95,
    description: "",
    category: "pants",
    picture: ["https://did.li/jMYYH", "https://did.li/AXqCN"],
  },
  {
    id: "14",
    itemName: "High Waist High Stretch Slant Pocket Jeans",
    price: 79,
    description: "",
    category: "pants",
    picture: ["https://did.li/9jlTY", "https://did.li/pvNw5"],
  },
  {
    id: "15",
    itemName: "Keyhole Back Allover Print Peplum Top",
    price: 40,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/yGfaa", "https://did.li/PRHNf"],
  },
  {
    id: "16",
    itemName: "Contrast Mesh High Waisted Bikini Swimsuit",
    price: 39,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/GGfaa", "https://did.li/XRHNf"],
  },
  {
    id: "17",
    itemName: "Cartoon Cat Print Drop Shoulder Blouse",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/VAwlC", "https://did.li/tXqCN"],
  },
  {
    id: "18",
    itemName: "Leopard Trim Bandeau High Waisted Bikini Swimsuit",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/veC5q", "https://did.li/e40ql"],
  },
  {
    id: "19",
    itemName: "Solid High Rise Straight Leg Pants",
    price: 69,
    description: "",
    category: "pants",
    picture: ["https://did.li/4AwlC", "https://did.li/Mp5Hw"],
  },
  {
    id: "20",
    itemName: "Leaf Pattern High Waisted Bikini Swimsuit",
    price: 39,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/HGfaa", "https://did.li/BXqCN"],
  },
  {
    id: "21",
    itemName: "Stonewash Distressed Skinny Jeans",
    price: 59,
    description: "",
    category: "pants",
    picture: ["https://did.li/YRHNf", "https://did.li/f40ql"],
  },
  {
    id: "22",
    itemName: "Highest-Rise Ripped Skinny Jeans",
    price: 59,
    description: "",
    category: "pants",
    picture: ["https://did.li/weC5q", "https://did.li/Np5Hw"],
  },
  {
    id: "23",
    itemName: "Geo Print Button Up Blouse",
    price: 40,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/2jlTY", "https://did.li/ivNw5"],
  },
  {
    id: "24",
    itemName: "Tie Dye High Waisted Bikini Swimsuit",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/lMYYH", "https://did.li/CXqCN"],
  },
  {
    id: "25",
    itemName: "One Shoulder Split Cuff Bodycon Dress",
    price: 39,
    description: "",
    category: "dresses",
    picture: ["https://did.li/JGfaa", "https://did.li/1RHNf"],
  },
  {
    id: "26",
    itemName: "Solid Flared Cami Dress",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["https://did.li/h40ql", "https://did.li/yeC5q"],
  },
  {
    id: "27",
    itemName: "Solid High Cut Bikini Swimsuit",
    price: 39,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/9RHNf", "https://did.li/p40ql"],
  },
  {
    id: "28",
    itemName: "Lapel Collar Pocket Blouse",
    price: 60,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/830ql", "https://did.li/oeC5q"],
  },
  {
    id: "29",
    itemName: "Sheer Mesh Overlay Hem Bustier Cami Dress",
    price: 69,
    description: "",
    category: "dresses",
    picture: ["https://did.li/Xp5Hw", "https://did.li/eBwlC"],
  },
  {
    id: "30",
    itemName: "Highest-Rise High Stretch Skinny Jeans",
    price: 50,
    description: "",
    category: "pants",
    picture: ["https://did.li/U9SfT", "https://did.li/bklTY"],
  },
  {
    id: "31",
    itemName: " Cheetah Print One-Shoulder Top",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/WAwlC", "https://did.li/dMYYH"],
  },
  {
    id: "32",
    itemName: "Floral Tie Side One Piece Swimsuit",
    price: 39,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/vMYYH", "https://did.li/MXqCN"],
  },
  {
    id: "33",
    itemName: "BASICS Single Breasted Solid Satin Blouse",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/uXqCN", "https://did.li/L9SfT"],
  },
  {
    id: "34",
    itemName: "MOTF PREMIUM MIDI WRAP BELTED DRESS",
    price: 119,
    description: "",
    category: "dresses",
    picture: ["https://did.li/Yp5Hw", "https://did.li/fBwlC"],
  },
  {
    id: "35",
    itemName: "Joyfunear Off Shoulder Split Bell Sleeve Dress",
    price: 69,
    description: "",
    category: "dresses",
    picture: ["https://did.li/49SfT", "https://did.li/kklTY"],
  },
  {
    id: "36",
    itemName: "High Waisted Ripped Skinny Jeans",
    price: 79,
    description: "",
    category: "pants",
    picture: ["https://did.li/BvNw5", "https://did.li/SGfaa"],
  },
  {
    id: "37",
    itemName: "Dual Pocket Button Up Blouse",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/3jlTY", "https://did.li/jvNw5"],
  },
  {
    id: "38",
    itemName: "Rib Cut-out One Piece Swimsuit",
    price: 47,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/q40ql", "https://did.li/HeC5q"],
  },
  {
    id: "39",
    itemName: "Twist Front Tie Back Crop Top",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/AGfaa", "https://did.li/RRHNf"],
  },
  {
    id: "40",
    itemName: "Rib Cut-out One Shoulder One Piece Swimsuit",
    price: 38,
    description: "",
    category: "dresses",
    picture: ["https://did.li/MBwlC", "https://did.li/4MYYH"],
  },
  {
    id: "41",
    itemName: "Solid Shirred Waist Dress",
    price: 53,
    description: "",
    category: "dresses",
    picture: ["https://did.li/kYqCN", "https://did.li/0vNw5"],
  },
  {
    id: "42",
    itemName: "Knot Side Shoulder Pads Fitted Dress",
    price: 41,
    description: "",
    category: "dresses",
    picture: ["https://did.li/qHfaa", "https://did.li/HSHNf"],
  },
  {
    id: "43",
    itemName: "Tie Back Leopard Top",
    price: 20,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/930ql", "https://did.li/peC5q"],
  },
  {
    id: "44",
    itemName: "Curvy Distressed Skinny Jeans",
    price: 60,
    description: "",
    category: "pants",
    picture: ["https://did.li/NBwlC", "https://did.li/wq5Hw"],
  },
  {
    id: "45",
    itemName: "Floral & Tropical One Piece Swimsuit",
    price: 49,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/C0SfT", "https://did.li/lYqCN"],
  },
  {
    id: "46",
    itemName: "Ruffle Sleeve One Piece Swimsuit",
    price: 57,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/rHfaa", "https://did.li/awNw5"],
  },
  {
    id: "47",
    itemName: "MOTF PREMIUM ASYMMETRICAL FLOWY DRESS",
    price: 129,
    description: "",
    category: "dresses",
    picture: ["https://did.li/NXqCN", "https://did.li/wMYYH"],
  },
  {
    id: "48",
    itemName: "Tie Neck Geo Print Blouse",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/Gp5Hw", "https://did.li/eMYYH"],
  },
  {
    id: "49",
    itemName: "Contrast Mesh Ruffle One Piece Swimsuit",
    price: 54,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/Z40ql", "https://did.li/gfC5q"],
  },
  {
    id: "50",
    itemName: "SXY High Waist Bleach Wash Skinny Jeans",
    price: 50,
    description: "",
    category: "pants",
    picture: ["https://did.li/D0SfT", "https://did.li/UklTY"],
  },
  {
    id: "51",
    itemName: "Appliques Maxi Chiffon Prom Dress",
    price: 174,
    description: "",
    category: "dresses",
    picture: ["https://did.li/140ql", "https://did.li/hfC5q"],
  },
  {
    id: "52",
    itemName: "MOTF PREMIUM 100% SILK GRADE 6A 22MM BLOUSE",
    price: 268,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/sHfaa", "https://did.li/JSHNf"],
  },
];
var theHeader = document.getElementsByTagName("header");
var imgLogoHome = document.getElementById("imgLogoHome");
var king = document.getElementById("king");

for (let i = 0; i < item.length; i++) {
  for (let j = 0; j < item[i].picture.length; j++) {
    
  }
}
