var item = [
  {
    id: "swblouse44201119103",
    itemName: "Notch Neck Puff Sleeve Ditsy Floral Blouse",
    price: 30,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/ORHNf", "https://did.li/630ql"],
  },
  {
    id: "swpants01201014455",
    itemName: "Paperbag Waist Dual Pocket Belted Skinny Pants",
    price: 60,
    description: "",
    category: "pants",
    picture: ["https://did.li/4jlTY", "https://did.li/kvNw5"],
  },
  {
    id: "swshorts25210407128",
    itemName: "Solid Slant Pocket Wide Leg Shorts",
    price: 40,
    description: "",
    category: "pants",
    picture: ["https://did.li/BGfaa", "https://did.li/030ql"],
  },
  {
    id: "swswim23200910668",
    itemName: "Cut-out One Shoulder Bikini Swimsuit",
    price: 49,
    description: "",
    category: "Swimwear",
    picture: ["https://did.li/fMYYH", "https://did.li/N9SfT"],
  },
  {
    id: "sw2108241225162181",
    itemName: "Satin Solid Button Through Drop Shoulder Blouse",
    price: 60,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/J9SfT", "https://did.li/hvNw5"],
  },
  {
    id: "sw2108038086418047",
    itemName: "Geo Print Ruffle Hem Shirt Dress",
    price: 80,
    description: "",
    category: "dresses",
    picture: ["https://did.li/5jlTY", "https://did.li/lvNw5"],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "sw2108100996259920",
    itemName: "",
    price: 40,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/yGfaa", "https://did.li/PRHNf"],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "sw2106215773396613",
    itemName: "Cartoon Cat Print Drop Shoulder Blouse",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/VAwlC", "https://did.li/tXqCN"],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "swblouse23210610831",
    itemName: "Geo Print Button Up Blouse",
    price: 40,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/2jlTY", "https://did.li/ivNw5"],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "swblouse02210406913",
    itemName: "Lapel Collar Pocket Blouse",
    price: 60,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/830ql", "https://did.li/oeC5q"],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "swblouse04190819068",
    itemName: " Cheetah Print One-Shoulder Top",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/WAwlC", "https://did.li/dMYYH"],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "swblouse07201024979",
    itemName: "BASICS Single Breasted Solid Satin Blouse",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/uXqCN", "https://did.li/L9SfT"],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "swblouse02210413670",
    itemName: "Dual Pocket Button Up Blouse",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/3jlTY", "https://did.li/jvNw5"],
  },

  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "swblouse04200721144",
    itemName: "Twist Front Tie Back Crop Top",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/AGfaa", "https://did.li/RRHNf"],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "swblouse07210527464",
    itemName: "Tie Back Leopard Top",
    price: 20,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/930ql", "https://did.li/peC5q"],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "pants",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "Swimwear",
    picture: ["", ""],
  },
  {
    id: "",
    itemName: "",
    price: 50,
    description: "",
    category: "dresses",
    picture: ["", ""],
  },
  {
    id: "swblouse23210513595",
    itemName: "Tie Neck Geo Print Blouse",
    price: 50,
    description: "",
    category: "Shirts",
    picture: ["https://did.li/Gp5Hw", "https://did.li/eMYYH"],
  },
];
var theBigDiv = document.getElementById("theBigDiv");
var body = document.getElementsByTagName("body");
